ren C:\WebDev\SDCEngine5\Models\breastcancer\breastCancerTnmStaging\breastCancerTnmStaging.json breastCancerTnmStaging.model.v1
ren C:\WebDev\SDCEngine5\Models\breastcancer\breastRiskAssessment\breastRiskAssessment.json breastRiskAssessment.model.v1
ren C:\WebDev\SDCEngine5\Models\breastcancer\FORM_BREAST_BMK\FORM_BREAST_BMK.json FORM_BREAST_BMK.model.v1
ren C:\WebDev\SDCEngine5\Models\cancer\cancer.json cancer.model.v1
ren C:\WebDev\SDCEngine5\Models\cancer\breastcancer\breastcancer.json breastcancer.model.v1
ren C:\WebDev\SDCEngine5\Models\cancer\breastcancer\breastCancerTnmStaging\breastCancerTnmStaging.json breastCancerTnmStaging.model.v1
ren C:\WebDev\SDCEngine5\Models\cancer\breastcancer\breastRiskAssessment\breastRiskAssessment.json breastRiskAssessment.model.v1
ren C:\WebDev\SDCEngine5\Models\cancer\breastcancer\FORM_Breast_Bmk\FORM_Breast_Bmk.json FORM_Breast_Bmk.model.v1
ren C:\WebDev\SDCEngine5\Models\cancer\testing\testing.json testing.model.v1
ren C:\WebDev\SDCEngine5\Models\sandbox\sandbox.json sandbox.model.v1
ren C:\WebDev\SDCEngine5\Models\sandbox\richardTest\richardTest.json richardTest.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\tooling.json tooling.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\cimcore\cimcore.json cimcore.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\cimi\cimi.json cimi.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\clinicalModel\clinicalModel.json clinicalModel.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\commonModel\commonModel.json commonModel.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\evinance\evinance.json evinance.model.v1
ren C:\WebDev\SDCEngine5\Models\tooling\penrad\penrad.json penrad.model.v1
